(()=>{const H={teto:{name:'Касане Тето',sub:'Багровый голос',css:'teto'},miku:{name:'Хацуне Мику',sub:'Бирюзовый сигнал',css:'miku'}};const $=x=>document.getElementById(x);let g,timer,drag=null;const fresh=()=>({hp:100,shield:0,hero:null,slots:[null,null,null,null],hand:[{type:'hero',id:'teto'},{type:'hero',id:'miku'}]});
function start(mode){g={mode,top:fresh(),bottom:fresh(),turn:null,ready:false,done:false};$('menu').classList.add('hidden');$('result').classList.add('hidden');$('coin').classList.add('hidden');$('battle').classList.remove('hidden');$('battle').classList.toggle('ai-battle',mode==='ai');$('top-label').textContent=mode==='ai'?'ПРОТИВНИК · ИИ':'ВЕРХНИЙ ИГРОК';$('mode-title').textContent=mode==='ai'?'БОЙ ПРОТИВ ИИ':'БОЙ РАЗРАБОТЧИКА';if(mode==='ai')setTimeout(()=>choose('top',Math.random()<.5?'teto':'miku'),400);render()}
function choose(s,id){if(g[s].hero)return;g[s].hero=H[id];g[s].hand=[{type:'attack',damage:25},{type:'generator'}];toast(`${g[s].hero.name} выходит на стол`);render();if(g.top.hero&&g.bottom.hero&&!g.ready)coinFlip()}
function coinFlip(){$('coin').classList.remove('hidden');$('coin-result').textContent='МОНЕТКА В ВОЗДУХЕ';const first=Math.random()<.5?'top':'bottom';setTimeout(()=>$('coin-result').textContent=(first==='top'?(g.mode==='ai'?'ИИ':'ВЕРХНИЙ ИГРОК'):'НИЖНИЙ ИГРОК')+' ХОДИТ ПЕРВЫМ',900);setTimeout(()=>{$('coin').classList.add('hidden');g.ready=true;begin(first)},1900)}
function begin(s){g.turn=s;if(g[s].slots.includes('generator')){g[s].shield=Math.min(50,g[s].shield+10);toast(`${s==='top'&&g.mode==='ai'?'ИИ':'Игрок'} получает 10 щита`)}render();if(g.mode==='ai'&&s==='top')setTimeout(aiTurn,650)}function pass(s){begin(s==='top'?'bottom':'top')}
function attack(s){const o=s==='top'?'bottom':'top',t=g[o];let d=25,b=Math.min(t.shield,d);t.shield-=b;d-=b;t.hp=Math.max(0,t.hp-d);animate(s,o);render();if(!t.hp){g.done=true;g.turn=null;$('winner').textContent=`${g[s].hero.name} побеждает`;setTimeout(()=>$('result').classList.remove('hidden'),430)}else pass(s)}
function place(s,i,handIndex){if(g[s].slots[i])return;g[s].slots[i]='generator';g[s].hand.splice(handIndex,1);toast('Генератор установлен');pass(s)}
function aiTurn(){if(!g||g.done||g.turn!=='top')return;const gi=g.top.hand.findIndex(c=>c.type==='generator'),kill=g.bottom.hp<=25;setTimeout(()=>{if(gi>=0&&!kill&&g.top.hp>25){const free=g.top.slots.map((x,i)=>x?null:i).filter(x=>x!==null);place('top',free[Math.floor(Math.random()*free.length)],gi)}else attack('top')},500)}
function targets(side,c){if(c.type==='hero')return!g[side].hero?[`${side}-hero`]:[];if(!g.ready||g.turn!==side)return[];if(c.type==='generator')return g[side].slots.map((x,i)=>x?null:`${side}-slot-${i}`).filter(Boolean);if(c.type==='attack'){const o=side==='top'?'bottom':'top';return g[o].hero?[`${o}-hero`]:[]}return[]}
function down(e){const el=e.target.closest('[data-card]');if(!el||!g||g.done)return;const side=el.dataset.side,index=+el.dataset.index,c=g[side].hand[index],valid=targets(side,c);if(!valid.length){toast('Сейчас эту карту разыграть нельзя');return}drag={side,index,c,valid,source:el,hover:null};el.classList.add('drag-source');const ghost=$('drag-ghost');ghost.innerHTML=el.outerHTML;ghost.classList.remove('hidden');valid.forEach(id=>$(id)?.classList.add('drop-valid'));move(e);e.preventDefault()}
function move(e){if(!drag)return;const x=Math.max(58,Math.min(innerWidth-58,e.clientX)),y=Math.max(75,Math.min(innerHeight-75,e.clientY)),ghost=$('drag-ghost');ghost.style.left=x+'px';ghost.style.top=y+'px';document.querySelectorAll('.drop-hover').forEach(n=>n.classList.remove('drop-hover'));const hit=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-drop]');if(hit&&drag.valid.includes(hit.id)){hit.classList.add('drop-hover');drag.hover=hit.id}else drag.hover=null;e.preventDefault()}
function up(e){if(!drag)return;const d=drag,id=d.hover;clear();if(!id)return toast('Розыгрыш отменён');if(d.c.type==='hero')choose(d.side,d.c.id);else if(d.c.type==='generator')place(d.side,+id.split('-').pop(),d.index);else attack(d.side);e.preventDefault()}function clear(){document.querySelectorAll('.drop-valid,.drop-hover,.drag-source').forEach(n=>n.classList.remove('drop-valid','drop-hover','drag-source'));$('drag-ghost').classList.add('hidden');$('drag-ghost').innerHTML='';drag=null}
function card(c,i,s){const a=`data-card data-side="${s}" data-index="${i}"`;if(c.type==='attack')return `<article class="card attack" ${a}><strong>⚔</strong><div><small>ВЕЧНАЯ</small><b>Атака</b><p>Урон: 25</p></div><em>25</em></article>`;if(c.type==='generator')return `<article class="card generator" ${a}><strong>⬡</strong><div><small>УСТРОЙСТВО</small><b>Генератор щита</b><p>Щит/ход: 10 · максимум: 50</p></div></article>`;const h=H[c.id];return `<article class="card ${h.css}" ${a}><div class="art"></div><div><small>ГЕРОЙ</small><b>${h.name}</b><p>HP: 100 · Щит: 0</p></div></article>`}
function hero(s){const p=g[s],el=$(`${s}-hero`);el.dataset.drop='hero';$(`${s}-name`).textContent=p.hero?p.hero.name:'Герой не выбран';if(!p.hero){el.className='hero empty';el.textContent='МЕСТО ГЕРОЯ'}else{el.className=`hero ${p.hero.css} ${g.turn===s?'active-turn':''}`;el.innerHTML=`<div class="portrait"></div><div><b>${p.hero.name}</b><p>${p.hero.sub}</p></div><div class="card-stats"><span class="stat-hp">♥ ${p.hp}</span><span class="stat-shield">⬡ ${p.shield}</span></div>`}}
function grid(s){return g[s].slots.map((x,i)=>`<div id="${s}-slot-${i}" class="grid-slot" data-drop="slot">${x?`<span class="field-card"><strong>⬡</strong><small>ГЕНЕРАТОР ЩИТА</small><b>+10 · ${g[s].shield}/50</b></span>`:''}</div>`).join('')}
function render(){['top','bottom'].forEach(s=>{hero(s);$(`${s}-grid`).innerHTML=grid(s);$(`${s}-hand`).innerHTML=g.mode==='ai'&&s==='top'?'':g[s].hand.map((c,i)=>card(c,i,s)).join('')});$('status').textContent=!g.top.hero||!g.bottom.hero?'ПЕРЕТАЩИ КАРТУ ГЕРОЯ':!g.ready?'БРОСОК МОНЕТКИ':g.turn==='top'?(g.mode==='ai'?'ХОД ИИ':'ХОД ВЕРХНЕГО ИГРОКА'):'ВАШ ХОД'}
function animate(a,b){const s=$(`${a}-hero`),t=$(`${b}-side`);s.classList.remove('cast');t.classList.remove('hit');void s.offsetWidth;s.classList.add('cast');setTimeout(()=>t.classList.add('hit'),100);setTimeout(()=>{s.classList.remove('cast');t.classList.remove('hit')},430)}function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('show'),1100)}function menu(){g=null;if(drag)clear();$('battle').classList.add('hidden');$('result').classList.add('hidden');$('coin').classList.add('hidden');$('menu').classList.remove('hidden')}
document.addEventListener('pointerdown',down);document.addEventListener('pointermove',move,{passive:false});document.addEventListener('pointerup',up);document.addEventListener('pointercancel',()=>drag&&clear());$('ai-mode').onclick=()=>start('ai');$('dev-mode').onclick=()=>start('dev');$('restart').onclick=menu;$('back').onclick=menu;})();
