(()=>{const H={teto:{name:'Касане Тето',sub:'Багровый голос',css:'teto'},miku:{name:'Хацуне Мику',sub:'Бирюзовый сигнал',css:'miku'}};const $=x=>document.getElementById(x);let g,timer;const fresh=()=>({hp:100,shield:0,hero:null,slots:[null,null,null,null],hand:[{type:'hero',id:'teto'},{type:'hero',id:'miku'}]});
function start(mode){g={mode,top:fresh(),bottom:fresh(),turn:null,ready:false,done:false,placement:null};$('menu').classList.add('hidden');$('result').classList.add('hidden');$('coin').classList.add('hidden');$('battle').classList.remove('hidden');$('battle').classList.toggle('ai-battle',mode==='ai');$('top-label').textContent=mode==='ai'?'ПРОТИВНИК · ИИ':'ВЕРХНИЙ ИГРОК';$('mode-title').textContent=mode==='ai'?'БОЙ ПРОТИВ ИИ':'БОЙ РАЗРАБОТЧИКА';if(mode==='ai')setTimeout(()=>choose('top',Math.random()<.5?'teto':'miku'),500);render()}
function choose(side,id){if(g.done||g[side].hero)return;g[side].hero=H[id];g[side].hand=[{type:'attack',damage:25},{type:'generator'}];toast(`${g[side].hero.name} выходит на стол`);render();if(g.top.hero&&g.bottom.hero&&!g.ready)coinFlip()}
function play(side,i){if(!g||g.done)return;const c=g[side].hand[i];if(!c)return;if(c.type==='hero'){choose(side,c.id);return}if(!g.ready)return toast('Сначала дождись броска монетки');if(g.turn!==side)return toast('Сейчас ход другой стороны');if(c.type==='generator'){g.placement={side,handIndex:i};toast('Теперь выбери свободную клетку');render();return}g.placement=null;attack(side)}
function place(side,slot){if(!g.placement||g.placement.side!==side||g.turn!==side)return;if(g[side].slots[slot])return toast('Эта клетка занята');g[side].slots[slot]='generator';g[side].hand.splice(g.placement.handIndex,1);g.placement=null;toast('Генератор щита установлен');pass(side)}
function coinFlip(){$('coin').classList.remove('hidden');$('coin-result').textContent='МОНЕТКА В ВОЗДУХЕ';const first=Math.random()<.5?'top':'bottom';setTimeout(()=>{$('coin-result').textContent=(first==='top'?(g.mode==='ai'?'ИИ':'ВЕРХНИЙ ИГРОК'):'НИЖНИЙ ИГРОК')+' ХОДИТ ПЕРВЫМ'},900);setTimeout(()=>{$('coin').classList.add('hidden');g.ready=true;begin(first)},1900)}
function begin(side){g.turn=side;g.placement=null;if(g[side].slots.includes('generator')){g[side].shield=Math.min(50,g[side].shield+10);toast(`${side==='top'&&g.mode==='ai'?'ИИ':'Игрок'} получает 10 щита`)}render();if(g.mode==='ai'&&side==='top')setTimeout(aiTurn,700)}function pass(side){begin(side==='top'?'bottom':'top')}
function attack(side){const other=side==='top'?'bottom':'top',target=g[other];let damage=25,blocked=Math.min(target.shield,damage);target.shield-=blocked;damage-=blocked;target.hp=Math.max(0,target.hp-damage);animate(side,other);render();if(!target.hp){finish(side);return}pass(side)}
function aiTurn(){if(!g||g.done||g.mode!=='ai'||g.turn!=='top')return;const gi=g.top.hand.findIndex(c=>c.type==='generator');const choices=[{type:'attack',score:25+(g.bottom.hp<=25?1000:0)}];if(gi>=0)choices.push({type:'generator',score:g.top.hp<=25?5:42});choices.sort((a,b)=>b.score-a.score);const c=choices[0];toast(c.type==='generator'?'ИИ выбирает место генератора':'ИИ атакует');setTimeout(()=>{if(c.type==='generator'){g.placement={side:'top',handIndex:gi};const free=g.top.slots.map((x,i)=>x?null:i).filter(x=>x!==null);place('top',free[Math.floor(Math.random()*free.length)])}else attack('top')},450)}
function finish(side){g.done=true;g.turn=null;$('winner').textContent=`${g[side].hero.name} побеждает`;setTimeout(()=>$('result').classList.remove('hidden'),450)}function animate(a,b){const s=$(`${a}-hero`),t=$(`${b}-side`);s.classList.remove('cast');t.classList.remove('hit');void s.offsetWidth;s.classList.add('cast');setTimeout(()=>t.classList.add('hit'),100);setTimeout(()=>{s.classList.remove('cast');t.classList.remove('hit')},430)}function toast(s){$('toast').textContent=s;$('toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('show'),1100)}
function card(c,i,s){if(c.type==='attack')return `<article class="card attack ${g.turn===s?'usable':''}"><strong>⚔</strong><div><small>ВЕЧНАЯ КАРТА</small><b>Атака</b><p>25 урона герою</p></div><em>25</em><button data-s="${s}" data-i="${i}">АТАКОВАТЬ</button></article>`;if(c.type==='generator')return `<article class="card generator ${g.turn===s?'usable':''}"><strong>⬡</strong><div><small>ОДНОРАЗОВАЯ КАРТА</small><b>Генератор щита</b><p>+10 в начале хода · максимум 50</p></div><button data-s="${s}" data-i="${i}">УСТАНОВИТЬ</button></article>`;const h=H[c.id];return `<article class="card ${h.css}"><div class="art"></div><div><small>КАРТА ГЕРОЯ</small><b>${h.name}</b><p>${h.sub}</p></div><button data-s="${s}" data-i="${i}">ВЫБРАТЬ</button></article>`}
function hero(s){const p=g[s],el=$(`${s}-hero`);$(`${s}-hp`).textContent=p.hp;$(`${s}-shield`).textContent=p.shield;$(`${s}-name`).textContent=p.hero?p.hero.name:'Герой не выбран';if(!p.hero){el.className='hero empty';el.textContent='ГЕРОЙ'}else{el.className=`hero ${p.hero.css} ${g.turn===s?'active-turn':''}`;el.innerHTML=`<div class="portrait"></div><div><b>${p.hero.name}</b><p>${p.hero.sub}</p></div>`}}
function grid(s){const selecting=g.placement&&g.placement.side===s;return g[s].slots.map((item,i)=>`<button class="grid-slot ${selecting&&!item?'available':''}" data-grid="${s}" data-slot="${i}">${item?`<span class="field-card"><strong>⬡</strong><small>ГЕНЕРАТОР</small><b>${g[s].shield}/50</b></span>`:''}</button>`).join('')}
function render(){['top','bottom'].forEach(s=>{hero(s);$(`${s}-grid`).innerHTML=grid(s);$(`${s}-hand`).innerHTML=g.mode==='ai'&&s==='top'?'':g[s].hand.map((c,i)=>card(c,i,s)).join('')});$('status').textContent=g.placement?'ВЫБЕРИ КЛЕТКУ ДЛЯ КАРТЫ':!g.top.hero||!g.bottom.hero?'ВЫБОР ГЕРОЕВ':!g.ready?'БРОСОК МОНЕТКИ':g.turn==='top'?(g.mode==='ai'?'ХОД ИИ':'ХОД ВЕРХНЕГО ИГРОКА'):'ВАШ ХОД';document.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>play(b.dataset.s,+b.dataset.i));document.querySelectorAll('[data-grid]').forEach(b=>b.onclick=()=>place(b.dataset.grid,+b.dataset.slot))}
function menu(){g=null;$('battle').classList.add('hidden');$('result').classList.add('hidden');$('coin').classList.add('hidden');$('menu').classList.remove('hidden')}$('ai-mode').onclick=()=>start('ai');$('dev-mode').onclick=()=>start('dev');$('restart').onclick=menu;$('back').onclick=menu;})();
