package com.evgenius.evgecardium;
import android.content.Context;import org.json.JSONObject;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.Locale;import java.util.concurrent.Executors;import java.util.zip.*;
final class UpdateManager{
 interface Listener{void progress(String m);void available(int v,String n);void current(int v);void installed(File f,int v);void error(String c,String d);}private static final long MAX=100L*1024*1024,MAX_FILE=30L*1024*1024;private final Context ctx;private final String channel;private final int bundled;private Listener listener;private JSONObject pending;
 UpdateManager(Context c,String u,int v){ctx=c;channel=u;bundled=v;ensureBundled();}int currentVersion(){return prefs().getInt("version",bundled);}File activeEntry(){File f=new File(root(),prefs().getString("slot","bundled")+"/index.html");return f.isFile()?f:new File(root(),"bundled/index.html");}
 void check(Listener l){listener=l;Executors.newSingleThreadExecutor().execute(()->{try{pending=new JSONObject(text(channel,262144,"E101"));int r=pending.getInt("version"),v=currentVersion();if(r<=v){l.current(v);return;}https(pending.getString("url"));https(pending.getString("sha256Url"));l.available(r,pending.optString("name","Content update"));}catch(Exception e){fail(e,"E109");}});}
 void installPending(){if(pending==null){listener.error("E110","Сначала нажми ПРОВЕРИТЬ");return;}Executors.newSingleThreadExecutor().execute(()->{try{int v=pending.getInt("version");listener.progress("Загрузка контрольной суммы…");String expected=text(pending.getString("sha256Url"),4096,"E201").trim().split("\\s+")[0];if(!expected.matches("(?i)[0-9a-f]{64}"))throw new UE("E202","Некорректный SHA-256");listener.progress("Загрузка игрового пакета v"+v+"…");byte[] zip=get(pending.getString("url"),MAX,"E203");String actual=hex(MessageDigest.getInstance("SHA-256").digest(zip));if(!actual.equalsIgnoreCase(expected))throw new UE("E204","SHA не совпал: "+actual.substring(0,12));String slot="slot-"+v;File dir=new File(root(),slot);del(dir);listener.progress("Проверка и распаковка…");unzip(zip,dir);File entry=new File(dir,pending.optString("entry","index.html"));if(!entry.isFile())throw new UE("E205","В архиве нет index.html");prefs().edit().putString("slot",slot).putInt("version",v).apply();listener.installed(entry,v);}catch(Exception e){fail(e,"E209");}});}
 private android.content.SharedPreferences prefs(){return ctx.getSharedPreferences("updates",0);}private File root(){return new File(ctx.getFilesDir(),"game");}private void ensureBundled(){File d=new File(root(),"bundled");if(!new File(d,"index.html").isFile())copyAssets("",d);}private void copyAssets(String p,File d){try{String[] a=ctx.getAssets().list(p);if(a==null)return;if(a.length==0){d.getParentFile().mkdirs();try(InputStream in=ctx.getAssets().open(p);OutputStream out=new FileOutputStream(d)){copy(in,out,MAX_FILE,"E301");}}else{d.mkdirs();for(String n:a)copyAssets(p.isEmpty()?n:p+"/"+n,new File(d,n));}}catch(Exception ignored){}}
 private static String text(String u,long m,String c)throws Exception{return new String(get(u,m,c),StandardCharsets.UTF_8);}private static byte[] get(String u,long m,String code)throws Exception{https(u);HttpURLConnection c=(HttpURLConnection)new URL(u).openConnection();c.setConnectTimeout(10000);c.setReadTimeout(30000);c.setRequestProperty("User-Agent","EvgeCardium-Updater/3");c.setInstanceFollowRedirects(true);try{int s=c.getResponseCode();if(s<200||s>=300)throw new UE(code,"HTTP "+s);try(InputStream in=c.getInputStream();ByteArrayOutputStream out=new ByteArrayOutputStream()){copy(in,out,m,code);return out.toByteArray();}}finally{c.disconnect();}}private static void copy(InputStream in,OutputStream out,long max,String code)throws Exception{byte[] b=new byte[16384];long t=0;for(int n;(n=in.read(b))>=0;){t+=n;if(t>max)throw new UE(code,"Превышен лимит размера");out.write(b,0,n);}}
 private static void unzip(byte[] z,File d)throws Exception{d.mkdirs();String root=d.getCanonicalPath()+File.separator;try(ZipInputStream in=new ZipInputStream(new ByteArrayInputStream(z))){for(ZipEntry e;(e=in.getNextEntry())!=null;){File f=new File(d,e.getName());if(!f.getCanonicalPath().startsWith(root))throw new UE("E206","Опасный путь в ZIP");if(e.isDirectory()){f.mkdirs();continue;}f.getParentFile().mkdirs();try(OutputStream out=new FileOutputStream(f)){copy(in,out,MAX_FILE,"E207");}}}}private static void https(String u)throws UE{if(!u.startsWith("https://"))throw new UE("E102","Разрешён только HTTPS");}private static String hex(byte[] b){StringBuilder s=new StringBuilder();for(byte x:b)s.append(String.format(Locale.US,"%02x",x));return s.toString();}private static void del(File f){if(!f.exists())return;File[] a=f.listFiles();if(a!=null)for(File x:a)del(x);f.delete();}private void fail(Exception e,String fallback){listener.error(e instanceof UE?((UE)e).code:fallback,e.getClass().getSimpleName()+(e.getMessage()==null?"":" · "+e.getMessage()));}private static final class UE extends Exception{final String code;UE(String c,String m){super(m);code=c;}}
}
